package:
  name: __name__
  version: "__version__"

source:
  path: __path__

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False
__noarch__

requirements:
  build:
    - python>=3.6,<4.0
    - setuptools 
    - pip
__build_requirements__
  
  run:
    - python>=3.6,<4.0
__dependencies__

