name: test-and-publish
on:
  push:
    branches:
      - develop
jobs:
  openergy:
    uses: openergy/github-actions-workflows/.github/workflows/test-and-publish-package.yml@master
    secrets:
      AZURE_CONDA_CHANNEL_KEY: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
